### PR TITLE
update dependencies in basic-login branch

### PR DESCRIPTION
**Pull request by hummusonrails**

### CODE REVIEW

**Comment by mheap** [comment]
I don't see any updates in here for:

* activerecord
* actionview
* activejob

They were listed as vulnerable in the notification too

**Comment by mheap** [comment]
This will need applying to the `two-factor` branch too, and https://www.nexmo.com/blog/2016/06/07/two-factor-authentication-2fa-ruby-rails-devise-nexmo-verify/ needs updating to use Rails 5

**Comment by hummusonrails** [comment]
This has been applied to the `two-factor` branch and I'll take a look at the blog post and suggest there the appropriate updates.

**Comment by mheap** [comment]
@benhayehudi Any updates required to the blog post, or can this be merged?

**Comment by hummusonrails** [comment]
@mheap - The post is all good. It can be merged.

**Pull request merged**
